export const liveChatData = [
  {
    username: "Alice",
    message: "Hey everyone! Excited for the new iPhone launch! 🎉",
    timestamp: "2024-09-25T12:00:00Z",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
    likes: 5,
  },
  {
    username: "Bob",
    message: "Hello! Can't wait to see the new features. 😃",
    timestamp: "2024-09-25T12:01:15Z",
    image: "https://randomuser.me/api/portraits/men/2.jpg",
    likes: 3,
  },
  {
    username: "Charlie",
    message: "Hi from Tokyo! Loving the event!",
    timestamp: "2024-09-25T12:02:30Z",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    likes: 4,
  },
  {
    username: "Diana",
    message: "Question: Will the new iPhone have a better camera?",
    timestamp: "2024-09-25T12:03:45Z",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    likes: 2,
    replies: [
      {
        username: "Ethan",
        message: "Great question, Diana! I'm curious too.",
        timestamp: "2024-09-25T12:04:00Z",
        image: "https://randomuser.me/api/portraits/men/5.jpg",
        likes: 1,
      },
    ],
  },
  {
    username: "Fiona",
    message: "Shoutout to all the new subscribers! 🙌",
    timestamp: "2024-09-25T12:05:30Z",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    likes: 6,
  },
  {
    username: "George",
    message: "This is my first live stream here. Hi everyone!",
    timestamp: "2024-09-25T12:06:45Z",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
    likes: 2,
    replies: [
      {
        username: "Hannah",
        message: "Welcome, George! You're going to love it here.",
        timestamp: "2024-09-25T12:07:00Z",
        image: "https://randomuser.me/api/portraits/women/8.jpg",
        likes: 3,
      },
    ],
  },
  {
    username: "Ian",
    message: "The design looks sleek! Can't wait to get my hands on it.",
    timestamp: "2024-09-25T12:08:15Z",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    likes: 5,
  },
  {
    username: "Julia",
    message: "Do you think the battery life will be improved?",
    timestamp: "2024-09-25T12:09:30Z",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    likes: 1,
  },
  {
    username: "Kevin",
    message: "I'm hoping for some new colors! 🎨",
    timestamp: "2024-09-25T12:10:45Z",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
    likes: 4,
  },
  {
    username: "Laura",
    message: "The presentation is so well done! 👏",
    timestamp: "2024-09-25T12:12:00Z",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    likes: 3,
  },
  {
    username: "Mike",
    message: "Does anyone know the release date?",
    timestamp: "2024-09-25T12:13:15Z",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
    likes: 2,
  },
  {
    username: "Nina",
    message: "I'm definitely pre-ordering as soon as it's available.",
    timestamp: "2024-09-25T12:14:30Z",
    image: "https://randomuser.me/api/portraits/women/14.jpg",
    likes: 4,
  },
  {
    username: "Oscar",
    message: "The new features are amazing! 😍",
    timestamp: "2024-09-25T12:15:45Z",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
    likes: 5,
  },
  {
    username: "Paula",
    message: "I wonder how much it will cost.",
    timestamp: "2024-09-25T12:17:00Z",
    image: "https://randomuser.me/api/portraits/women/16.jpg",
    likes: 1,
  },
  {
    username: "Quinn",
    message: "The camera specs are impressive!",
    timestamp: "2024-09-25T12:18:15Z",
    image: "https://randomuser.me/api/portraits/men/17.jpg",
    likes: 3,
  },
  {
    username: "Rachel",
    message: "Can't wait to see the performance benchmarks.",
    timestamp: "2024-09-25T12:19:30Z",
    image: "https://randomuser.me/api/portraits/women/18.jpg",
    likes: 2,
  },
  {
    username: "Sam",
    message: "This is the best iPhone launch event yet!",
    timestamp: "2024-09-25T12:20:45Z",
    image: "https://randomuser.me/api/portraits/men/19.jpg",
    likes: 4,
  },
  {
    username: "Tina",
    message: "Thanks for the stream! Loving the updates. 😊",
    timestamp: "2024-09-25T12:22:00Z",
    image: "https://randomuser.me/api/portraits/women/20.jpg",
    likes: 3,
  },
  {
    username: "Moderator",
    message: "Please keep the chat respectful and on-topic. Thank you!",
    timestamp: "2024-09-25T12:23:00Z",
    image: "https://randomuser.me/api/portraits/men/21.jpg",
  },
];
